---
# File:        roles/incinga2-web/tasks/main.yml
# Created:     16.04.2017
# Author:      Thomas Galliker
# Email:       mail@thomasgalliker.net
# Description: Incinga web


- name: "Ensure all components for icinga-web are installed"
  become: yes
  apt:
      name: "{{ item }}"
      state: present
  with_items:
      - icinga2-ido-pgsql
      - icingaweb2


- name: "Ensure incinga postgresql user is present"
  become: yes
  become_user: "{{ postgres_default_user }}"
  postgresql_user:
      name: "{{ icinga_postgres_user }}"
      password: "{{ icinga_postgres_password }}"


- name: "Ensure incinga db is present"
  become: yes
  become_user: "{{ postgres_default_user }}"
  postgresql_db:
      name: "{{ icinga_db_name }}"
      owner: "{{ icinga_postgres_user }}"
      encoding: UTF-8


#- name: "Grant privilegs to incinga user"
#  become: yes
#  become_user: "{{ postgres_default_user }}"
#  postgresql_privs:
#      db: "{{ icinga_db_name }}"
#      privs: ALL
#      type: database
#      role:  "{{ icinga_postgres_user }}"


- name: "Create DB Initial DB Schema( to create set varriable, initialize_icinga_db: true)"
  become: yes
  shell: "export PGPASSWORD={{ icinga_postgres_password }} && psql -U {{ icinga_postgres_user }} -d {{ icinga_db_name }} < {{ icinga_db_schema }}"
  when: "{{ initialize_icinga_db }}"


- name: "Setup ido conf"
  become: yes
  template:
      src: ido-pgsql.conf.j2
      dest: /etc/icinga2/features-available/ido-pgsql.conf
      owner: nagios
      group: nagios
      mode: 0640
  notify:
    - restart icinga

- name: "Enable icinga ido-pgsql"
  become: yes
  file:
      src: ../features-available/ido-pgsql.conf
      dest: /etc/icinga2/features-enabled/ido-pgsql.conf
      state: link
      owner: root
      group: root
      mode: 0644
  notify:
    - restart icinga


- name: "Ensure incinga postgresql user is present"
  become: yes
  become_user: "{{ postgres_default_user }}"
  postgresql_user:
      name: "{{ icingaweb_postgres_user }}"
      password: "{{ icingaweb_postgres_password }}"


- name: "Ensure incinga web db is present"
  become: yes
  become_user: "{{ postgres_default_user }}"
  postgresql_db:
      name: "{{ icingaweb_db_name }}"
      owner: "{{ icingaweb_postgres_user }}"
      encoding: UTF-8


- name: "Create DB Initial DB Schema( to create set varriable, initialize_icinga_db: true)"
  become: yes
  shell: "export PGPASSWORD={{ icingaweb_postgres_password }} && psql -U {{ icingaweb_postgres_user }} -d {{ icingaweb_db_name }} < {{ icingaweb_db_schema }}"
  when: "{{ initialize_icinga_db }}"
