---
# File: 	roles/domainmember/tasks/main.yml
# Created:	03.05.2016
# Description:  Configuration of Python for development
# Author: 	Thomas Galliker
# Email:	mail@thomasgalliker.net

- name: "Make sure follwing packages are present"
  become: yes
  apt: name={{ item }}
       state=present
  with_items:
    - krb5-user
    - libnss-winbind
    - libpam-krb5
    - libpam-mount
    - libpam-winbind
    - samba
    - smbclient
    - cifs-utils

- name: Copy configuration files
  sudo: yes
  copy: src=../files{{ item }} dest={{ item }} owner=root group=root mode=644
  with_items:
    - /etc/krb5.conf
    - /etc/samba/smb.conf
    - /etc/nsswitch.conf
    - /etc/security/pam_mount.conf.xml
