---
# File:        roles/apache2/tasks/main.yml
# Created:     16.04.2017
# Author:      Thomas Galliker
# Email:       mail@thomasgalliker.net
# Description: Apache2


- name: "Ensure all components for apache2 are installed"
  become: yes
  apt:
      name: "{{ item }}"
      state: present
  with_items:
      - apache2
      - php5-imagick
      - php5-pgsql
      - php5-intl
  notify:
      - restart apache2


- name: "Ensure php config"
  become: yes
  copy:
      src: php.ini
      dest: /etc/php5/apache2/php.ini
      owner: root
      group: root
      mode: 0644
  notify:
      - restart apache2
