---
# File:        tasks/interfaces.yml
# Created:     03.06.2017
# Author:      Thomas Galliker
# Email:       mail@thomasgalliker.net
# Description: Configure network interfaces


- name: "Install bridge-utils if bridge is defined"
  become: true
  apt:
      name: bridge-utils
      state: present
  when: interfaces_bridge is defined

- name: "Configure network interfaces"
  become: true
  template:
      src: interfaces.j2
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: 0644
