---
# File:        tasks/mount_cifs.yml
# Created:     16.04.2017
# Author:      Thomas Galliker
# Email:       mail@thomasgalliker.net
# Description: Mount cifs shares


- name: "Ensure all needed packages nfs are installed"
  become: true
  apt: 
      name: "{{ item }}"
      state: present
  with_items:
      - nfs-common


- name: "Make sure all nfs mountpoints are there"
  become: true
  file:
    path: "{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: 400
  with_items: "{{ common_mount.nfs.mountpoints | default([]) }}"


- name: "Make sure all nfs mountpoints update in fstab"
  become: true
  mount:
    name: "{{ item.path }}"
    src: "{{ item.share_path }}"
    fstype: nfs
    opts: "{{ item.options }}"
    state: present
  with_items: "{{ common_mount.nfs.mountpoints | default([]) }}"
