---
# file: roles/common/tasks/main.yml
#

- name: "Ensure packages neede for Ansible are installed"
  become: yes
  apt: 
      name: "{{ item }}"
      state: present
  with_items:
      - aptitude
      - apt-transport-https

- name: "Update chache"
  become: yes
  apt: 
      update_cache: yes
      upgrade: safe
      cache_valid_time: 3600

- name: "Install common administrativ tools"
  become: yes
  apt: 
      name: "{{ item }}"
      state: present
  with_items:
    - vim
    - tmux
