---
# File:        roles/bind/tasks/main.yml
# Created:     17.04.2017
# Author:      Thomas Galliker
# Email:       mail@thomasgalliker.net
# Description: Install Bind Server

- name: "Ensure bind is installed"
  become: true
  apt: 
    name: bind9
    state: present

- name: "Ensure named.conf.options is updatet"
  become: true
  template:  
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: 0644
  notify:
    - restart dns


- name: "copy named.conf.local"
  become: true
  template:  
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local
    owner: root
    group: bind
    mode: 0644
  notify:
    - restart dns


- name: "copy zone files"
  become: true
  template:
    src: db.j2
    dest: "/var/lib/bind/db.{{ item.name }}"
    owner: bind
    group: bind
    mode:  0644
  with_items: "{{ dns_zones }}"
  notify:
    - restart dns
