---
# File:        roles/incinga2/tasks/main.yml
# Created:     16.04.2017
# Author:      Thomas Galliker
# Email:       mail@thomasgalliker.net
# Description: Incinga server configuration

- name: "Ensure Incinga apt key is present"
  become: yes
  apt_key:
      url: "https://packages.icinga.com/icinga.key"
      state: present


- name: "Ensure Incinga source is present"
  become: yes
  apt_repository:
      repo: "deb https://packages.icinga.com/debian icinga-jessie main"
      state: present
      filename: 'incinga'
      update_cache: yes

- name: "Ensure incinga2 is installed"
  become: yes
  apt:
      name: "{{ item }}"
      state: present
  with_items:
      - icinga2
      - nagios-plugins
#      - graphite-web
#      - graphite-carbon
#
#
#- name: "Enable icinga feature: api"
#  become: yes
#  file:
#      src: ../features-available/api.conf
#      dest: /etc/icinga2/features-enabled/api.conf
#      state: link
#      owner: root
#      group: root
#      mode: 0644
#  notify:
#    - restart icinga
#
#- name: "Copy apache2 grpahite-web config"
#  become: yes
#  copy:
#    src: graphite.conf
#      dest: /etc/apache2/sites-available/graphite.conf
#      owner: root
#      group: root
#      mode: 0644
#
#- name: "a2ensite graphite"
#  become: yes
#  command: a2ensite graphite
#  args:
#    creates: /etc/apache2/sites-enabled/graphite.conf
