---
# File:        server.yml
# Created:     18.04.2017
# Author:      Thomas Galliker
# Email:       mail@thomasgalliker.net
# Description: Playbook to config Servers

- name: "Configuration for all servers"
  hosts: server
  roles:
    - common
    - common-server

- include: kvm_server.yml
- include: dhcp_server.yml
- include: dns_server.yml
- include: monitoring_server.yml
