---
# file: roles/mysql-server/tasks/main.yml

- name: "Ensure MySql Server is installed."
  apt: name=mysql-server
       state=present

- name: "Ensure my.conf is present"
  template: src=my.j2 
            dest=/root/.my.conf 
            owner=root
            group=root
            mode=0600

- name: "Ensure the backupuser is present"
  mysql_user: name=backup
              password={{ mysql_backup_user_password }}
              priv=*.*:ALL 
              state=present
